# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1085bc24ac44667744288be253f59d853cd8c2dcb4cdf27cde989f4b53bf1d455b12e31bc3d672821a157855bcd21a35682dc1650fb744c345ad97b83e6c1353

test:
  secret_key_base: 0008c8e8f6496aed57f612b18338f848750e932aa962e15a0b605adb42f918f05e5f598aae83c18188e6f560b83c2e70c11672112196d1dea493e7f0797a30ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
